export const SHORTCUT_EVENTS = {
  focusCurrencySearch: "fx:focus-currency-search",
  swapCurrencies: "fx:swap-currencies",
  setRateRange: "fx:set-rate-range",
  toggleShortcutsHelp: "fx:toggle-shortcuts-help",
  selectRecentPair: "fx:select-recent-pair",
  fillTestCredentials: "fx:fill-test-credentials",
  favoriteActivePair: "fx:favorite-active-pair",
  logActivePair: "fx:log-active-pair",
  openAlertPopover: "fx:open-alert-popover",
  shareActivePair: "fx:share-active-pair",
  toggleTheme: "fx:toggle-theme",
  switchTab: "fx:switch-tab",
  toggleCompareView: "fx:toggle-compare-view",
  exportLogCsv: "fx:export-log-csv",
  openCompareCurrencyPicker: "fx:open-compare-currency-picker",
  copyRate: "fx:copy-rate",
  focusAmountInput: "fx:focus-amount-input",
} as const;
